### ISSUE TITLE
License of the icons

### ISSUE THREAD

**Issue by muratcorlu** [Tarkeasy/round-flags#3]
Hello!

What is the source and license of the icons? Did you draw them or do you redistribute an icon library someone else has created?

**Comment by Tarkeasy** [comment]
> Hello!
> 
> What is the source and license of the icons? Did you draw them or do you redistribute an icon library someone else has created?

Hello!
These icons were gotten from the web site with free to use svgs. (Sorry I don't remember how it called) I collected all these svgs into the library.

**Comment by muratcorlu** [comment]
Thanks for the reply. The reason I'm asking is, we want to use this SVGs in our projects: https://www.figma.com/community/file/986015950111698581/Round-world-flags Author(@diegomorra) allows to use it by giving credits. I was planning to publish them as a NPM package by crediting the author but noticed some similar ones like yours. I also tried to reach the author of the SVGs but couldn't manage yet. I don't know if the SVGs in your repository is the same but just trying to determine best way of using those assets. It's tricky ☺️
